validators using metaprogramming
mayuriv-webonise/ruby_traning pull request #7
Opened 2023-08-11 13:18 UTC by mayuriv-webonise

2023-08-11 13:27 UTC, balakrishna-webonise requested changes

2023-08-11 13:27 UTC, balakrishna-webonise commented on validators.rb
> +  end
Pls add a new line between the methods

2023-08-11 13:27 UTC, balakrishna-webonise commented on validators.rb
> +          if value.nil? || (value.respond_to?(:empty?) && value.empty?)
value.blank?

2023-08-11 13:27 UTC, balakrishna-webonise commented on validators.rb
> +          if value.respond_to?(:length) && value.length < 5
value&.length < 5

&. - Please read about Ruby safe operator

2023-08-11 13:27 UTC, balakrishna-webonise commented on validators.rb
> +          if attribute == :age && (value.nil? || value < 18)
.presence evaluates first right as per your input.
You do not need to check .nil? here again

2023-08-11 13:27 UTC, balakrishna-webonise commented on validators.rb
> +end
Pls add new line between the classes

2023-08-11 13:27 UTC, balakrishna-webonise commented on validators.rb
> +  attr_accessor :name, :email, :age
new line. It should be readable

2023-08-11 13:39 UTC, mayuriv-webonise commented on validators.rb
> +  end
added

2023-08-11 13:39 UTC, mayuriv-webonise commented on validators.rb
> +          if value.nil? || (value.respond_to?(:empty?) && value.empty?)
added change

2023-08-16 08:34 UTC, balakrishna-webonise commented on validators.rb
> +          if value.nil? || (value.respond_to?(:empty?) && value.empty?)
I do not see the changes for this

2023-08-16 09:41 UTC, balakrishna-webonise approved these changes

2023-08-16 09:42 UTC, merged